FROM leloubil/beammp:latest

MAINTAINER Bilel MEDIMEGH, bilel.medimegh@gmail.com

RUN adduser --disabled-password --home /home/container container

RUN chmod -R 777 /BeamMP

USER container

ENV USER=container HOME=/home/container

WORKDIR /home/container

COPY ./pterodactyl-entrypoint.sh /entrypoint.sh

CMD ["/bin/bash", "/entrypoint.sh"]
