name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup docker
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push base image
      id: docker_build_base
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: leloubil/beammp:latest
        file: ./Dockerfile
    - name: Build and push pterodactyl image
      id: docker_build_pterodactyl
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: leloubil/beammp:pterodactyl
        file: ./Dockerfile.pterodactyl
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: leloubil/beammp
      
